disabled_rules:
 - trailing_whitespace
 - weak_delegate
 - type_name

# rule identifiers to opt in
opt_in_rules:
 - closure_end_indentation
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - fatal_error_message
 - first_where
 - force_unwrapping
 - implicitly_unwrapped_optional

#custom rules
custom_rules:
  no_prints: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: "No prints in commits" # rule name. optional.
    regex: "([p,P]rint)" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "Please remove before commit" # violation message. optional.
  mockup: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: "Mockup data being used" # rule name. optional.
    regex: "([m,M]ock)" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "You're using mocked up data in the project." # violation message. optional.

# special configuration for rules 
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false
  
type_body_lenght:
    warning: 500
    error: 600

file_length:
  warning: 400
  error: 1000

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 12

implicitly_unwrapped_optional:
  mode: allExceptIBOutlets

function_body_length:
  warning: 45
  error: 100

line_length:
  warning: 200
  error: 220
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  min_length:
    warning: 0
    error: 2
  max_length: # only min_length
    error: 30 # only error
  excluded: # excluded via string array
    - i
