# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace


# special configuration for rules 
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

file_length:
  warning: 400
  error: 1000

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 12

implicitly_unwrapped_optional:
  mode: allExceptIBOutlets

function_body_length:
  warning: 45
  error: 100

line_length:
  warning: 180
  error: 220
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true

