//
//  PhotoPickerDelegate.swift
//  MacroPepelelipa
//
//  Created by Leonardo Oliveira on 20/10/20.
//  Copyright © 2020 Pedro Giuliano Farina. All rights reserved.
//

#if !targetEnvironment(macCatalyst)

import UIKit
import PhotosUI

internal class PhotoPickerDelegate: NSObject, PHPickerViewControllerDelegate {
    
    // MARK: - Variables and Constants
    
    private var didFinishPickingImage: ((UIImage?, Error?) -> Void)?
    
    // MARK: - Initializers
    
    internal init(_ didFinishPickingResults: @escaping (UIImage?, Error?) -> Void) {
        self.didFinishPickingImage = didFinishPickingResults 
    }
    
    // MARK: - PHPickerViewControllerDelegate functions
    
    internal func picker(_ picker: PHPickerViewController, didFinishPicking results: [PHPickerResult]) {
        picker.dismiss(animated: true)
        getImage(from: results)
    }
    
    // MARK: - Functions
    
    /// This method gets the selected image from the results generated by picker
    private func getImage(from results: [PHPickerResult]) {
        
        var result: (image: UIImage?, error: Error?)
        
        if let itemProvider = results.first?.itemProvider, itemProvider.canLoadObject(ofClass: UIImage.self) {
            itemProvider.loadObject(ofClass: UIImage.self) { (loadedImage, error) in
                
                if let image = loadedImage as? UIImage {
                    result = (image, nil)
                }
                
                if let error = error {
                    result = (nil, error)
                }
                
                self.didFinishPickingImage?(result.image, result.error)
            }
        }
    }
}

#endif
